- name: java
  hosts: 127.0.0.1
  connection: local


  vars:
    java_version: 17
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution_release_fallback:
      'jammy': 'jammy'


  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux
    - name: Add linuxuprising APT package key
      become: yes
      get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1CC3D16E460A94EE17FE581CEA8CACC073C3DB2A
        dest: /etc/apt/keyrings/linuxuprising-java.asc
        mode: 0644


    - name: Add Oracle Java
      become: yes
      apt_repository:
        repo: deb [arch=amd64, signed-by=/etc/apt/keyrings/linuxuprising-java.asc] https://ppa.launchpadcontent.net/linuxuprising/java/{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) | lower }} {{ distribution_release_fallback[ansible_distribution_release] | default(ansible_distribution_release) }} main
        filename: oracle-linuxuprising-java
        update_cache: no
      register: apt_repository


    - name: Accept Oracle Java license
      become: yes
      debconf:
        name: 'oracle-java{{ java_version }}-installer'
        question: 'shared/accepted-oracle-license-v1-3'
        value: 'true'
        vtype: 'select'


    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Oracle Java JDK
      become: yes
      apt:
        name: 'oracle-java{{ java_version }}-installer'
        state: present
        install_recommends: false




