- name: neovim
  hosts: 127.0.0.1
  connection: local

  vars:
    neovim_version: "0.12.3"
    neovim_appimage: "nvim-linux-x86_64.appimage"


  tasks:
    - name: Creating neovim folder
      become: yes
      file:
        path: /opt/nvim
        state: directory

    - name: Download neovim
      delegate_to: localhost
      become: yes
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/{{ neovim_appimage }}"
        dest: "/opt/nvim"
        headers:
          Accept: "application/octet-stream"
        mode: 0755

    - name: Create symlink to /usr/local/vim
      become: yes
      file:
        path: /usr/local/bin/vim
        src: "/opt/nvim/{{ neovim_appimage }}"
        state: link

    - name: Create symlink to /usr/local/nvim
      become: yes
      file:
        path: /usr/local/bin/nvim
        src: "/opt/nvim/{{ neovim_appimage }}"
        state: link



